services:
  - type: web
    name: registro-conferencias
    runtime: python3
    repo: https://github.com/PABLO9307/jornadas-asistencia
    plan: free
    rootDir: jornadas-asistencia
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
